### ISSUE TITLE
Warning compilation

### ISSUE THREAD

**Issue by Owned67** [popoklopsi/Ingame-Map-Download#1]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// mapdownload.sp
//
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(9
57) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(9
58) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(9
59) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(9
60) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(9
62) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(1
212) : warning 213: tag mismatch
// G:\cstrike\addons\sourcemod\scripting\mapdownload.sp(1
222) : warning 213: tag mismatch
// Code size:            79524 bytes
// Data size:           245988 bytes
// Stack/heap size:      16384 bytes
// Total requirements:  341896 bytes
//
// 7 Warnings.
//
// Compilation Time: 0,76 sec
// ----------------------------------------

Press enter to exit ...

**Comment by ghost** [comment]
This is because of the new API. I didn't rewrite it for the new syntax, yet. But it shouldn't be a problem.
