### ISSUE TITLE
broken again

### ISSUE THREAD

**Issue by e54385991** [popoklopsi/Ingame-Map-Download#12]
Unable to grab anything

**Comment by dordnung** [comment]
Gamebanana added a request limit for their API, so there is now always appearing a "429 Too Many Requests" ... 
For the first I'll stop supporting this, until they maybe remove that limit

**Comment by e54385991** [comment]
Yes, I don'’t use threads now.

**Comment by dordnung** [comment]
For me it also do not work when not using threads
