### ISSUE TITLE
ERROR: Couldn't get map information. Skipping...

### ISSUE THREAD

**Issue by Breadwinka** [popoklopsi/Ingame-Map-Download#16]
When built from latest source get the above error.

![image](https://user-images.githubusercontent.com/13487931/57644666-9b1fcd00-758a-11e9-9441-bc2bd15cff9e.png)

**Comment by dordnung** [comment]
Gamebanana changed their API a lot, so currently I can't use it and I do not have time to migrate the lister to the new API
