### ISSUE TITLE
Crash on start if mapdownload activated

### ISSUE THREAD

**Issue by Owned67** [popoklopsi/Ingame-Map-Download#2]
with:

VAC secure mode is activated.
L 11/29/2015 - 03:29:56: [mapdownload.smx] Updated gamebanana Database succesfully!
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
dimanche 29 novembre 2015, 03:29:57 (UTC+0100): Server restart in 10 seconds
dimanche 29 novembre 2015, 03:29:59 (UTC+0100): Server Quit

without:
Connection to Steam servers successful.
   Public IP is XXX.XXX.XXX.XX.
Assigned persistent gameserver Steam ID [G:1:29525].
VAC secure mode is activated.

**Comment by ghost** [comment]
I do not have any problems. What version of the system2 extension and sourcemod do you use?

`VAC secure mode is activated.
L 11/29/2015 - 13:11:11: [mapdownload.smx] Updated gamebanana Database succesfully!
sm plugins list
[SM] Listing 18 plugins:
  01 "Ingame Map Download" (2.2.1) by Popoklopsi`

**Comment by Owned67** [comment]
MetaMod:Source v1.11.0-dev+998V, 
SourceMod v1.7.3
87 "Ingame Map Download" (2.2.1) by Popoklopsi
System2 (2.32): System Commands and Information

Plugin is loaded but only at start, crash it.... if disable your plugin, my server don't crash...

**Comment by ghost** [comment]
Do you solved the problem? Because your log does not help, sorry
