### ISSUE TITLE
Maps not downloading

### ISSUE THREAD

**Issue by reubenbrr** [popoklopsi/Ingame-Map-Download#3]
Hi, I'm having an issue where no maps are downloading despite the ingame download looking fine.
Not getting any errors and the downloads look fine but the file is not appearing anywhere.

Is there any troubleshooting I can do for this?

**Comment by ghost** [comment]
Sorry for the late replay. Do you solved the problem?

**Comment by reubenbrr** [comment]
No, it seems to be not working at all. No matter how I try to do it the map does not get downloaded :cry:

**Comment by ghost** [comment]
Does it say successfully installed in the chat after you downloaded it?

**Comment by reubenbrr** [comment]
Nope, the progress bar just fills up and then disappears when it reaches 100%. No confirmation message

**Comment by ghost** [comment]
Do you got any files in sourcemod/data/mapdownload?
