### ISSUE TITLE
Gamebana binary dont work

### ISSUE THREAD

**Issue by carlosflorencio** [popoklopsi/Ingame-Map-Download#4]
Hi,

The binary gives an error after choosing counter strike source, maybe the api from gamebana has changed.

Thanks

**Comment by ghost** [comment]
I just forgot to upload the latest binaries. It should now work correctly

**Comment by carlosflorencio** [comment]
Thanks! Its working now.

I had this error after installing the plugin on a cs:s server:
L 01/20/2016 - 01:52:24: Info (map "de_dust2") (file "errors_20160120.log")
L 01/20/2016 - 01:52:24: [mapdownload.smx] Map Download couldn't prepare the Database. Error: 'file is encrypted or is not a database'

I have installed System2 Extension and given the right permissions to the executables by ftp.
I will try to add the generated database from the binary to the server and try again.

**Comment by ghost** [comment]
Sorry, i think this happend because the update site was offline

**Comment by carlosflorencio** [comment]
Will test again, thanks!
