### ISSUE TITLE
Download .bsp files

### ISSUE THREAD

**Issue by the133448** [popoklopsi/Ingame-Map-Download#5]
Is there anyway to download a .bsp file from an  url? At the moment you can only download compressed url files

**Comment by dordnung** [comment]
I've added this now, have fun :)

**Comment by popoklopsi** [comment]
I've added this now, have fun :)

**Comment by dordnung** [comment]
I've added this now, have fun :)

**Comment by dordnung** [comment]
I've added this now, have fun :)
