### ISSUE TITLE
Compile Warnings (warning 213: tag mismatch)

### ISSUE THREAD

**Issue by Nomy** [popoklopsi/Ingame-Map-Download#6]
//// mapdownload.sp
//
// mapdownload.sp(978) : warning 213: tag mismatch
// mapdownload.sp(979) : warning 213: tag mismatch
// mapdownload.sp(980) : warning 213: tag mismatch
// mapdownload.sp(981) : warning 213: tag mismatch
// mapdownload.sp(983) : warning 213: tag mismatch
// mapdownload.sp(1233) : warning 213: tag mismatch
// mapdownload.sp(1243) : warning 213: tag mismatch
// Code size:            79124 bytes
// Data size:           245656 bytes
// Stack/heap size:      16384 bytes
// Total requirements:  341164 bytes
//
// 7 Warnings.
//
// Compilation Time: 0.53 sec
// ----------------------------------------

**Comment by dordnung** [comment]
These errors appear because I'm not using the new syntax API, yet . You can ignore them.
