### ISSUE TITLE
gamebanana api broken

### ISSUE THREAD

**Issue by e54385991** [popoklopsi/Ingame-Map-Download#8]
https://api.gamebanana.com/Core/Item/Data?itemtype=Map&itemid=19745&fields=catid,date,mdate,downloads,name,rating,votes,views,Downloadable().sFileUrl(),Downloadable().nGetFilesize()

Unrecognized [fields] `Downloadable().sFileUrl()` and `Downloadable().nGetFilesize()`", "error_code": "INVALID_FIELDS_PARAM" }

**Comment by dordnung** [comment]
Oh no, why did they remove this... Thanks for the hint.

**Comment by dordnung** [comment]
I've made it working again
