### ISSUE TITLE
Binary exit 

### ISSUE THREAD

**Issue by e54385991** [popoklopsi/Ingame-Map-Download#9]
CSGO Categories

ERROR: Couldn't insert category (INSERT OR IGNORE INTO `mapdl_categories_v2` (`id`, `name`, `game`) VALUES (, 'Surf Style', 'csgo'):near ",": syntax error). Program seems to be outdated...

C:\Users\e5438\Desktop\maplister\msvc17\Release>

**Comment by dordnung** [comment]
Weird problem, but is fixed
